version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: lakshmi123
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306" # Keep external port 3307
    networks:
      - student-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"] # Change localhost to mysql
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      - student-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: lakshmi123

networks:
  student-network:
    driver: bridge

volumes:
  mysql-data:




